# config.yaml

# slcio2edm4hep_validate_crawler.py
# TODO: to be changed for full dress rehearsal
slcio_path: "/afs/cern.ch/user/c/chensel/cernbox/ILC/HtoInv/MC/pilot_samples"
slcio_conversion_options: "--dry-run"

# define paths, samples, parameters
# the following lines are examples
# TODO: update keys with correct values and/or keys

samples: ["signal", "background1", "background2"]
paths:
  lcio: "data/lcio"
  edm4hep: "data/edm4hep"
  analysis: "results/analysis"
  plots: "results/plots"

  



transformations:
  convert:
    script: scripts/convert_lcio.py
    output_dir: edm4hep
  analysis:
    script: scripts/analysis.py
    output_dir: ntuples

helper_files:
  all_mc: data/all_files.txt
