# config.yaml

# slcio2edm4hep_validate_crawler.py
# TODO: to be changed for full dress rehearsal
slcio_path: "/afs/cern.ch/user/c/chensel/cernbox/ILC/HtoInv/MC/pilot_samples"
slcio_conversion_options: "--dry-run"

# Global configuration for Snakemake workflow

paths:
  # Input/output structure
  master_lfn_list: "inputs/all_files.txt"              # input list of all LFNs
  lfn_list: "outputs/lfn_list.txt"                     # filtered LFN list
  preprocess_dir: "outputs/preprocess"                 # fetched LFNs
  converted_dir: "outputs/converted"                   # LCIO -> ROOT outputs
  prod_ids: "outputs/production_ids.txt"               # unique production IDs
  mc_xsec_yaml: "outputs/mc_xsec.yaml"                 # cross-section master file
  job_yaml_dir: "outputs/job_yamls"                    # Condor job yamls
  key4hep_dir: "outputs/key4hep"                       # Key4hep job configs + outputs
  analysis_output: "outputs/analysis"                  # physics analysis outputs
  plots: "outputs/plots"                               # final plots
  summary: "outputs/summary"                           # final summary tables/reports
